POWERS = [
    "AC +2d6",
    "AC +1d10",
    "AC +1d12",
    "AC +1d12, Immune to Normal Weapons",
    "AC +1d20",
    "AC +1d4",
    "AC +1d6",
    "AC +1d6, Immune to Normal Weapons",
    "AC +1d8",
    "AC +1d8, Immune to Normal Weapons",
    "Animated Dead (At Will)",
    "Blurred (Always on. First Attack Against Creature Always Misses, Otherwise +2 AC)",
    "Bonus Attack (If initial Attack Hits, Opportunity for Another Attack)",
    "Bonus Damage on Great Hit (does One Greater Die Damage if hits by 5 or More or Natural 20)",
    "Chaos (At Will, One At a Time)",
    "Cloudkill (at Will, One at a Time)",
    "Cold Attack (ranged, HDd6 Damage)",
    "Confusion (on Successful Hit)",
    "Continuing Damage (after a Hit, Victim Takes One Die Less Damage Each Round Until Creature Leaves or is Killed)",
    "Damage Sphere (All within 15' take d6 Damage per Round)",
    "Darkness Sphere (At Will, One at a Time)",
    "Detect Invisibility (Always On)",
    "Drain ability Score (on a Successful Hit)",
    "Duo-Dimension (Always On, but does Not take extra Damage)",
    "Electrical Attack (Ranged, HDd6 Damage)",
    "Energy Drain (On a Successful Hit)",
    "ESP (Always On)",
    "Explosion",
    "Feeblemind (On a successful Hit)",
    "Fire Attack (Ranged, HDd6 damage)",
    "Gaseous Form (At Will)",
    "Globe of invulnerability (Always on self)",
    "Grapple (+5 to Rolls Involving Grappling)",
    "Haste (Always on Self)",
    "Immune to Cold",
    "Immune to Electricity",
    "Immune to Fire",
    "Immune to Magic",
    "Immune to Metal",
    "Immune to Normal weapons",
    "Immune to Physical Attacks",
    "Immune to Wood",
    "Impregnates (Vicitims hit Must Save Versus Poison or Carry a Thing)",
    "Incendiary Cloud (At Will, One At a Time)",
    "Lost Dweomer",
    "magic Drain (On Successful hit)",
    "Maze (On a Successful Hit)",
    "Memory Wipe (On a Successful Hit, but no other Damage)",
    "Mimicry (Can Duplicate Sounds and Voices It has Heard)",
    "Mind Control (At Will, One at a Time)",
    "Mirror Image (Always On)",
    "Move Earth (At will)",
    "Multiple Attacks (Additional d3 Attacks)",
    "Paralysis (on a Successful Hit)",
    "Pernicious Wounds (Do not Naturally Heal)",
    "Phantasmal Force (At Will, One At a Time)",
    "Phantasmal Psychedelia (At Will, One at a Time)",
    "Phantasmal Supergoria (At will, One at a time)",
    "Phasing (Can Move Through Solid Objects)",
    "Plant Death (All Vegetation Dies within 10' x HD)",
    "Poison (on Successful Hit)",
    "Polymorph Other (On a Successful Hit)",
    "Prismatic Sphere (At Will)",
    "Prismatic Spray (at Will)",
    "Prismatic Wall (At Will, One at a Time)",
    "Psionic Attack (Auto-Hit, d6 Damage)",
    "Psionic Scream (Auto-Hit in 30' Radius Area, d6 Damage + Victims Must Save or be Slowed)",
    "Radiation Attack",
    "Radioactive",
    "Ranged Attack",
    "Regenerate (Regains d3hp a Round)",
    "Reverse Gravity (At Will, One at  A time)",
    "Silence (Always On in 15' Area)",
    "Slow (once Every Ten Rounds)",
    "Spell Turning (Always on)",
    "Spellcasting (As Magic user of 2d6 Levels - Random spells)",
    "Spore Cloud (All in Area Must Save Versus Poison or Become Infected)",
    "Stinking Cloud (Continuous Around Creature)",
    "Stone Shape (At Will)",
    "Summoning (As Per This Spell, no miscast, Creatures Under Control of this Creature, not Original Caster)",
    "Swallow Whole (on a natural 20 or hitting by 10 or More)",
    "Symbol (one type, randomly Determined at will)",
    "Telekenesis (at Will)",
    "Teleportation (at Will)",
    "Time Stop",
    "Transmute Flesh to Stone (on Successful hit)",
    "Transmute Rock to Mud (at Will)",
    "Valuable Innards (worth 500sp x HD)",
    "Ventriloquism (At Will)",
    "Victims Rise as Undead",
    "Vulnerable to Cold (Takes +1 Damage per Die)",
    "Vulnerable to Cold Iron (Takes +1 Damage per Die)",
    "Vulnerable to Electricity (takes +1 Damage per die)",
    "Vulnerable to Fire (takes +1 Damage per Die)",
    "Vulnerable to Metal (takes +1 Damage per die)",
    "Vulnerable to Physical Attacks (takes +1 Damage Per Die)",
    "Vulnerable to Silver (Takes +1 Damage Per Die)",
    "Vulnerable to Wood (takes +1 Damage Per die)",
    "Wall of Fire (At Will, One at a Time)",
    "Web (at Will, One at a Time)",
]

FORM = [
    {'name': "Amoeba", 'powers': []},
    {'name': "Balloon", 'powers': []},
    {'name': "Blood", 'powers': ["Immune to Normal Attacks"]},
    {'name': "Brain", 'powers': []},
    {'name': "Canine", 'powers': ["Move 180'"]},
    {'name': "Crab", 'powers': ["2 Attacks", "+2 AC"]},
    {'name': "Crystal", 'powers': ["+4 AC"]},
    {'name': "Excrement", 'powers': []},
    {'name': "Eyeball", 'powers': []},
    {'name': "Frog", 'powers': ["Leap 150'"]},
    {'name': "Fungus", 'powers': ["Move 60'"]},
    {'name': "Insectoid", 'powers': ["+2 AC"]},
    {'name': "Organic Rot", 'powers': ["Causes Disease on Hit"]},
    {'name': "Polyhedral", 'powers': []},
    {'name': "Seaweed", 'powers': []},
    {'name': "Slime", 'powers': ["Move 60'"]},
    {'name': "Snake", 'powers': ["50% Poison", "50% Constriction"]},
    {'name': "Squid", 'powers': []},
]

DEADLY_FORM = [
    {'name': "Anti-Matter", 'powers': ["HDd6 Explosion on Every Contact"]},
    {'name': "Dream-Matter", 'powers': ["All Touched Become Confused"]},
    {'name': "Flowing colors", 'powers': []},
    {'name': "Fog", 'powers': ["Immune to Normal Attacks"]},
    {'name': "Lightning", 'powers': ["Move 240'", "Immune to Normal Attacks", "d8 Damage Touch", "Touching it w/ Metal Does d8 Damage"]},
    {'name': "Orb of Light", 'powers': ["Immune to Normal Attacks"]},
    {'name': "Pure Energy", 'powers': ["Immune to Normal Attacks", "Touch does d8 Damage"]},
    {'name': "Shadow", 'powers': []},
    {'name': "Smoke", 'powers': ["Immune to Normal Attacks", "Move 240'"]},
    {'name': "Wind", 'powers': ["Immune to Normal Attacks", "Move 240'"]},
]

ABSTRACT_FORM = [
    {'name': "Collective Unconscious Desire for Suicide", 'powers': []},
    {'name': "Fear of a Blackened Planet", 'powers': []},
    {'name': "Imaginary Equation, Incorrect yet True", 'powers': []},
    {'name': "Lament of a Mother for Her Dead Child", 'powers': []},
    {'name': "Lust of a Betrayed Lover", 'powers': []},
    {'name': "Memories of Pre-Conception", 'powers': []},
    {'name': "Regret for Unchosen Possibilities", 'powers': []},
    {'name': "Space Between the Ticks of a Clock", 'powers': []},
]

APENDAGE_ADJECTIVE = [
	"Adhesive",
	"Beautiful",
	"Bestial",
	"Chiming",
	"Crystaline",
	"Dead",
	"Dripping",
	"Fanged",
	"Flaming",
	"Furred",
	"Gigantic",
	"Glowing",
	"Gossamer",
	"Gushing",
	"Humming",
	"Icy",
	"Immaterial",
	"Incomplete",
	"Malformed",
	"Necrotic",
	"Negative",
	"Neon",
	"Numerous",
	"Petrified",
	"Prehensile",
	"Pungent",
	"Reflective",
	"Rubbery",
	"Running",
	"Skeletal",
	"Slimy",
	"Smoking",
	"Stalked",
	"Thorned",
	"Throbbing",
	"Transparent",
]

APENDAGE_NOUN = [
	"Antennae",
	"Arms",
	"Branches",
	"Claws",
	"Eggs/Seeds",
	"Eyes/Great eye",
	"Face",
	"Feathers",
	"Fins",
	"Flowers",
	"Foliage",
	"Fronds",
	"Genitals",
	"Horn",
	"Legs",
	"Lumps",
	"Machine",
	"Maggots",
	"Mandibles",
	"Mouths/Great Maw",
	"Oil",
	"Proboscis",
	"Pseudopods",
	"Scales",
	"Shell",
	"Sores",
	"Spine",
	"Stinger",
	"Stripes",
	"Suction Pods",
	"Tail",
	"Teats",
	"Teeth",
	"Tentacles",
	"Wings",
	"Wrapping",
]

DOMINATION_FAILURES = [
    "The creature retreats to its own reality, bringing the caster back with it. The caster's physical body is destroyed but his mental essence exists in misery forever.",
    "The creature's presence in this universe is stable and it will not be drawn back to its world. The caster's will is replaced with that of the creature, and the character becomes an NPC. If the creature and the Magic User have the strength to destroy everyone and everything in their immediate surroundings, they will do so. If there is doubt about their ability to accomplish this, the creature and caster will retreat and begin their long-range campaign to  bring Hell on Earth.",
    "The creature holds the rift open longer than the caster intended; d10 more creatures with Hit Dice ranging from 1 to the summoned creature's Hit Dice, flood into the physical world. They will attempt to slay and consume every living thing.",
    "The creature and the Caster merge to form one being. It may switch between the two physical forms at will, and in either form possesses all the powers of both beings. The creature is in control.",
    "The creature explodes on contact with our universe, disrupting all sense of self and identity. All characters within 120' are randomly switched into new bodies, with the levels and class abilities of the new body (all bodies must change, even if the random roll puts a character back in their original body). All present are now Chaotic in alignment, and any Clerics lose their Cleric spells.",
    "The creature is not at all interested in being in 'reality' nor does it care about anyone present. It is however supremely vexed at being called through the veil by a piece of meat. It will take one of the caster's comrades as compensation. The caster must choose one of his  fellow PCs and then that character will simply cease to be. If the caster delays, or chooses anyone else than a Player Character, then all the PCs in the area will be winked out of existence... and the caster will be left alone.",
]

